#!/usr/bin/env bash
#
# Alucurv ERP — first-time deploy script.
#
# Idempotent: aman dijalankan ulang. Akan generate .env baru kalau belum ada,
# build & start container, push Prisma schema, lalu seed kalau database masih
# kosong. Existing data tidak akan di-wipe.
#
# Usage (di VM Linux baru):
#   curl -O https://raw.githubusercontent.com/TsukasaCh/erp/main/scripts/deploy.sh
#   chmod +x deploy.sh && ./deploy.sh
#
# Atau setelah git clone:
#   bash scripts/deploy.sh
#
set -euo pipefail

# ----- helpers --------------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log()  { echo -e "${BLUE}▶${NC} $*"; }
ok()   { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}⚠${NC} $*"; }
err()  { echo -e "${RED}✗${NC} $*" >&2; exit 1; }

# ----- prerequisites --------------------------------------------------------
log "Checking prerequisites..."
command -v docker >/dev/null 2>&1 || err "docker tidak terinstall. Run: curl -fsSL https://get.docker.com | sh"
docker compose version >/dev/null 2>&1 || err "docker compose plugin tidak ada. Install: sudo apt install docker-compose-plugin"
command -v openssl >/dev/null 2>&1 || err "openssl dibutuhkan untuk generate secret. Run: sudo apt install openssl"
ok "Docker $(docker --version | cut -d' ' -f3 | tr -d ',') · compose $(docker compose version --short)"

# ----- repo check -----------------------------------------------------------
if [[ ! -f docker-compose.yml ]]; then
  err "docker-compose.yml tidak ditemukan. Pastikan run dari root repo (cd ke folder erp dulu)."
fi

# ----- .env setup -----------------------------------------------------------
if [[ -f .env ]]; then
  ok ".env sudah ada (skip generate). Lo bisa edit manual kalau perlu."
else
  log "Generate .env baru dengan secret random..."

  # Detect SEMUA IP yang available:
  # - Public IP (visible dari internet, lewat ipify)
  # - Private/LAN IP (172.x, 192.168.x, 10.x — untuk akses internal)
  # - localhost (kalau lo cuma test di server itu sendiri)
  PUBLIC_IP=$(curl -s --max-time 3 https://api.ipify.org 2>/dev/null || true)

  # Private IP: ambil semua IP non-loopback dari hostname -I (Linux only)
  PRIVATE_IPS=""
  if command -v hostname >/dev/null 2>&1; then
    PRIVATE_IPS=$(hostname -I 2>/dev/null | tr ' ' '\n' | grep -E '^(10\.|172\.(1[6-9]|2[0-9]|3[0-1])\.|192\.168\.)' | head -3 | tr '\n' ' ' || true)
  fi

  echo ""
  echo "  Detected:"
  [[ -n "$PUBLIC_IP" ]]   && echo "    Public IP  : $PUBLIC_IP"
  [[ -n "$PRIVATE_IPS" ]] && echo "    Private IP : $PRIVATE_IPS"
  echo "    Localhost  : localhost / 127.0.0.1"
  echo ""
  echo "  Pilih host yang user akses untuk buka aplikasi (frontend → API):"
  echo "    [1] Public IP  (akses dari internet)"
  echo "    [2] Private IP (akses LAN/VPN saja, mis. 172.16.0.62)"
  echo "    [3] localhost  (cuma di server ini)"
  echo "    [4] Custom (ketik manual — domain, dll)"
  echo ""

  DEFAULT_CHOICE="1"
  [[ -z "$PUBLIC_IP" && -n "$PRIVATE_IPS" ]] && DEFAULT_CHOICE="2"

  read -rp "Pilihan [$DEFAULT_CHOICE]: " CHOICE
  CHOICE="${CHOICE:-$DEFAULT_CHOICE}"

  case "$CHOICE" in
    1)
      [[ -z "$PUBLIC_IP" ]] && err "Public IP tidak terdeteksi. Pilih opsi lain atau cek koneksi internet."
      VM_HOST="$PUBLIC_IP"
      ;;
    2)
      if [[ -z "$PRIVATE_IPS" ]]; then
        err "Private IP tidak terdeteksi. Cek dengan: hostname -I"
      fi
      # Kalau ada beberapa private IP, kasih sub-pilihan
      PRIVATE_ARR=($PRIVATE_IPS)
      if [[ ${#PRIVATE_ARR[@]} -eq 1 ]]; then
        VM_HOST="${PRIVATE_ARR[0]}"
      else
        echo ""
        for i in "${!PRIVATE_ARR[@]}"; do
          echo "    [$((i+1))] ${PRIVATE_ARR[$i]}"
        done
        read -rp "Pilih private IP [1]: " PIDX
        PIDX="${PIDX:-1}"
        VM_HOST="${PRIVATE_ARR[$((PIDX-1))]}"
      fi
      ;;
    3)
      VM_HOST="localhost"
      ;;
    4)
      read -rp "Ketik host (mis. erp.alucurv.com atau IP lain): " VM_HOST
      [[ -z "$VM_HOST" ]] && err "Host wajib diisi."
      ;;
    *)
      err "Pilihan tidak valid"
      ;;
  esac
  ok "Host yang dipakai: ${VM_HOST}"

  PG_PASS=$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-32)
  JWT=$(openssl rand -base64 48 | tr -d '/+=' | cut -c1-48)

  cat > .env <<EOF
# Generated by deploy.sh on $(date)
POSTGRES_USER=alucurv
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=alucurv_erp
JWT_SECRET=${JWT}
NEXT_PUBLIC_API_BASE=http://${VM_HOST}:3000
EOF
  chmod 600 .env
  ok ".env created (mode 600). VM_HOST=${VM_HOST}"
fi

# Source it for current session
set -a; source .env; set +a

# ----- build & start --------------------------------------------------------
log "Building containers (ini bisa makan 3-5 menit pertama kali)..."
docker compose build --pull
ok "Build done"

log "Starting containers..."
docker compose up -d
ok "Containers up"

# ----- wait for postgres ----------------------------------------------------
log "Waiting for PostgreSQL to be ready..."
for i in {1..30}; do
  if docker compose exec -T postgres pg_isready -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" >/dev/null 2>&1; then
    ok "PostgreSQL ready"
    break
  fi
  sleep 2
  if [[ $i -eq 30 ]]; then err "PostgreSQL tidak ready setelah 60 detik"; fi
done

# ----- wait for api ---------------------------------------------------------
log "Waiting for API to be ready..."
for i in {1..30}; do
  if docker compose exec -T api node -e "require('http').get('http://localhost:3000/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))" >/dev/null 2>&1; then
    ok "API ready"
    break
  fi
  sleep 2
  if [[ $i -eq 30 ]]; then err "API tidak ready setelah 60 detik. Cek: docker compose logs api"; fi
done

# ----- prisma push schema ---------------------------------------------------
log "Pushing Prisma schema (bikin tabel kalau belum ada)..."
docker compose exec -T api npx prisma db push --skip-generate
ok "Schema pushed"

# ----- seed (idempotent: skip kalau sudah ada produk) -----------------------
log "Running seed (akan skip kalau data sudah ada)..."
docker compose exec -T api npm run seed:prod
ok "Seed done"

# ----- summary --------------------------------------------------------------
echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  DEPLOY SUKSES${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo ""
echo "  Frontend  : http://${VM_HOST:-localhost}:3001"
echo "  API       : http://${VM_HOST:-localhost}:3000/health"
echo "  Login     : admin / Tanggor25@   (LANGSUNG GANTI password setelah login)"
echo ""
echo "  Status    : docker compose ps"
echo "  Logs      : docker compose logs -f api"
echo "  Update    : bash scripts/update.sh"
echo "  Backup    : bash scripts/backup.sh"
echo ""
echo -e "${YELLOW}⚠  PENTING:${NC}"
echo "  1. Buka firewall: sudo ufw allow 3000 && sudo ufw allow 3001"
echo "  2. Setup cron daily backup (lihat scripts/backup.sh)"
echo "  3. Login & ganti password admin DULU"
echo ""
